import json
from pathlib import Path

days_file = Path("research/at-98-days.json")
with open(days_file, encoding="utf-8") as f:
    days = json.load(f)

lines = []
lines.append("---")
lines.append('title: "Walking 2,178 Miles in 98 Days: My Appalachian Trail Log, Ultralight Gear, and Field Notes"')
lines.append('description: "2,178 miles in 98 days at a 22.5 mile daily average with a 5.73-pound base weight. The complete state-by-state log, gear list, and data charts from Georgia to Maine."')
lines.append("pubDate: 2026-09-20")
lines.append('tags: ["essays", "travel"]')
lines.append("---")
lines.append("")
lines.append("In the summer of 2009, I took a Greyhound bus to Gainesville, Georgia, shared a taxi to Springer Mountain, and started walking north to Maine.")
lines.append("")
lines.append("Most Appalachian Trail thru-hikers take five to six months. I wanted to see what would happen if I treated the trail as a high-mileage physical and logistical problem rather than a relaxed summer stroll. I hiked 2,178.3 miles in 98 days, averaging 22.48 miles per day with an ultralight pack base weight of 5.73 pounds.")
lines.append("")
lines.append("This is the complete record of that hike: the daily distance data, the exact gear list, state-by-state observations, and the physical reality of moving fast over mountain terrain.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Key Numbers at a Glance")
lines.append("")
lines.append("The daily numbers below come directly from my hiking log:")
lines.append("")
lines.append("| Metric | Recorded Value |")
lines.append("| :--- | :--- |")
lines.append("| **Route** | Springer Mountain, Georgia to Mount Katahdin, Maine |")
lines.append("| **Total Distance** | 2,178.3 cumulative miles |")
lines.append("| **Hiking Days** | 98 days (May 21 to August 26, 2009) |")
lines.append("| **Overall Average Pace** | 22.48 miles per day |")
lines.append("| **Sample Standard Deviation** | 5.04 miles |")
lines.append("| **Marathon Days (26.2+ miles)** | 20 days |")
lines.append("| **Days Over 30 Miles** | 6 days |")
lines.append("| **Longest Single Day** | 33.2 miles (Day 29, Wapiti Shelter, VA) |")
lines.append("| **Shortest Single Day** | 5.2 miles (Day 98, Katahdin summit, ME) |")
lines.append("| **Pack Base Weight** | 5.73 pounds (91.75 oz) |")
lines.append("")
lines.append("![Cumulative Miles: 98-Day Actual vs Standard 150-Day Thru-Hike](/images/at/at-cumulative-pace-chart.svg)")
lines.append("")
lines.append("A standard 5-month thru-hike moves at about 14.5 miles per day. By Day 98, an average thru-hiker is around southern Pennsylvania or Massachusetts. Moving at 22.5 miles per day compresses the timeline, but it requires dialing in pack weight, food resupply, and daily routine.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## The 5.73-Pound Ultralight Gear Setup")
lines.append("")
lines.append("In 2009, ultralight backpacking was far less common than it is today. Carrying a base weight under 6 pounds required stripping away almost everything that outdoor retailers marketed as mandatory.")
lines.append("")
lines.append("I used a 19-ounce frameless pack, slept under a 5x7 flat silnylon tarp, and cooked over a homemade alcohol can stove that weighed half an ounce. If an item did not prevent hypothermia, keep water potable, or keep my feet moving, it stayed off the packing list.")
lines.append("")
lines.append("![Jack's 5.73 lb Base Weight Breakdown](/images/at/at-gear-weight-breakdown.svg)")
lines.append("")
lines.append("### Complete Itemized Pack Weight")
lines.append("")
lines.append("| Category | Item | Weight (oz) | Notes |")
lines.append("| :--- | :--- | :--- | :--- |")
lines.append("| **Pack** | GoLite Jam Backpack | 19.0 | Frameless, simple roll-top pack |")
lines.append("| **Sleep** | Marmot Pounder Sleeping Bag | 17.0 | Synthetic 40F bag, fast-drying |")
lines.append("| **Sleep** | RidgeRest 3/4 Foam Pad | 9.4 | Closed-cell foam, trimmed to length |")
lines.append("| **Shelter** | Silnylon Flat Tarp (5ft x 7ft) | 7.5 | Pitched with trekking poles |")
lines.append("| **Weather** | DriDucks Rain Jacket | 5.7 | Fragile but waterproof and breathable |")
lines.append("| **Electronics** | Digital Camera with battery | 9.1 | Carried for photos and journal notes |")
lines.append("| **Clothing** | Extra Darn Tough Socks | 3.5 | Worn in rotation to prevent blisters |")
lines.append("| **Shelter** | Titanium / Aluminum Tent Stakes (6) | 2.8 | Ground anchors for tarp guyouts |")
lines.append("| **Lighting** | Petzl Headlamp with batteries | 2.7 | Used for night hiking and camp setups |")
lines.append("| **Hydration** | 2x Platypus 1.8L Reservoirs | 2.2 | Collapsible, zero empty weight |")
lines.append("| **Protection** | Heavy-Duty Pack Liner Bag | 2.1 | Kept sleeping bag dry inside pack |")
lines.append("| **Water** | Aquamira Water Treatment Drops | 2.0 | Chemical chlorine dioxide drops |")
lines.append("| **Hygiene** | Dr. Bronner's Liquid Soap | 2.0 | Multi-use washing |")
lines.append("| **Tools** | Leatherman Micra Multi-Tool | 1.7 | Scissors and small blade |")
lines.append("| **Shelter** | Polycro Plastic Groundsheet | 1.5 | Window-insulation plastic barrier |")
lines.append("| **Storage** | Silnylon Stuff Sacks | 1.2 | Ditty bags for food and loose gear |")
lines.append("| **Food Hang** | Spectra Bear Bag Cord | 1.0 | 50ft lightweight cord |")
lines.append("| **Kitchen** | Homemade Alcohol Can Stove | 0.5 | Built from an aluminum soda can |")
lines.append("| **Essentials** | ID, debit card, cash | 0.4 | Town stops and permits |")
lines.append("| **Kitchen** | Light Plastic Spoon | 0.2 | Eating utensils |")
lines.append("| **Kitchen** | Mini Lighter and Waterproof Matches | 0.2 | Stove ignition |")
lines.append("| **Total Base Weight** | **All 20 Pack Items** | **91.75 oz** | **5.73 pounds total** |")
lines.append("")
lines.append("On my body, I wore Montrail trail runners (22.3 oz), running shorts (5.2 oz), a cycling jersey (4.0 oz), and Darn Tough socks (2.1 oz), while carrying Leki trekking poles (18.0 oz).")
lines.append("")
lines.append("### What Held Up and What Failed")
lines.append("")
lines.append("The 5x7 tarp required careful site selection. If wind whipped rain sideways during an exposed ridge storm, spray was unavoidable. But pitching it low in dense trees kept me dry through downpours from Georgia to Maine.")
lines.append("")
lines.append("The DriDucks jacket tore easily against briars, requiring duct tape patches, but it cost under $20 and breathed far better than heavy proprietary shells. Trail runners caused early foot soreness, but they dried within thirty minutes of creek crossings, while heavy leather boots remained sodden for days.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Daily Mileage Dynamics: 20 Marathons and 6 Days Over 30 Miles")
lines.append("")
lines.append("Maintaining a 22.5 mile average on rugged terrain is not about sprinting. It is about continuous movement. I woke at dawn, started walking within fifteen minutes, took short fifteen-minute food breaks, and walked until dusk.")
lines.append("")
lines.append("![Daily Mileage Across 98 Days](/images/at/at-daily-mileage-chart.svg)")
lines.append("")
lines.append("Key patterns from the daily record:")
lines.append("")
lines.append("- **Early ramp:** I opened with 15.1 miles on Day 1, reached 22.0 miles on Day 2, and hit 24.0 miles by Day 9 in the Great Smoky Mountains.")
lines.append("- **The Mid-Atlantic speedway:** Days 24 to 70 across Virginia, Maryland, Pennsylvania, and New Jersey were the fastest stretches of the hike. Terrain flattened out, trail legs were fully conditioned, and 25-to-30-mile days became standard.")
lines.append("- **The 30-plus mile club:** 6 days exceeded 30 miles, peaking at 33.2 miles on Day 29 to Wapiti Shelter and 32.1 miles on Day 42 to Rock Spring Hut in Shenandoah.")
lines.append("- **The rugged Northern slowdown:** Mileage dropped sharply in the White Mountains of New Hampshire (Day 77 to 83) and southern Maine (Day 84 to 88). Mahoosuc Notch and vertical granite climbs cut daily pace down to 18 to 20 miles despite hiking full 12-hour days.")
lines.append("")
lines.append("![Average Daily Mileage by State](/images/at/at-state-mileage-bars.svg)")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## State-by-State Field Notes: Springer to Katahdin")
lines.append("")
lines.append("### 1. Georgia (Days 1 to 4 | 79.3 miles | 20.7 mi/day)")
lines.append("Georgia wastes no time. The climbs start immediately out of Springer Mountain, steep, humid, and rocky. My feet started hurting on day one, a dull ache that never completely disappeared for the next three months.")
lines.append("")
lines.append("That first week was about learning how to exist outdoors. I learned how to pitch my tarp cleanly, how to keep sleeping insulation dry in steady downpours, and how to eat constant calories while moving.")
lines.append("")
lines.append("### 2. North Carolina and the Smokies (Days 5 to 14 | 192.5 miles | 18.9 mi/day)")
lines.append("The balds in North Carolina delivered the first panoramic views. Max Patch felt like an open meadow floating above the clouds. But open ridgelines also meant watching severe thunderstorms roll in from miles away with nowhere to shelter.")
lines.append("")
lines.append("In the Great Smoky Mountains, cold rain, shelter rules, and severe stomach sickness hit around Day 11. Pushing through 20-mile days with fever and nausea was miserable, but stopping in wet woods felt worse than walking toward town.")
lines.append("")
lines.append("### 3. Tennessee (Days 15 to 23 | 179.5 miles | 24.7 mi/day)")
lines.append("Hot Springs and Damascus marked the first true trail town resets. Real food, grocery stores, and hot showers made a massive psychological difference. I ate double orders of diner food, pizza, and ice cream.")
lines.append("")
lines.append("By Roan Mountain and the Highlands, my body had adapted. Daily soreness became background noise, and 24 to 28 miles felt sustainable from morning to night.")
lines.append("")
lines.append("### 4. Virginia (Days 24 to 45 | 538.8 miles | 24.5 mi/day)")
lines.append("Virginia is massive, making up one-quarter of the entire trail. It plays tricks on your head because you walk for three weeks and remain in the same state.")
lines.append("")
lines.append("This was my fastest extended block. On Day 26, I hiked 30.6 miles to Partnership Shelter and ordered delivery pizza directly to the trail. On Day 29, I hit my hike-wide record of 33.2 miles to Wapiti Shelter. Shenandoah National Park brought paved waysides, blackberry milkshakes, and Day 42's 32.1-mile push.")
lines.append("")
lines.append("### 5. West Virginia and Maryland (Days 46 to 48 | 69.5 miles | 23.2 mi/day)")
lines.append("Crossing the pedestrian bridge into Harpers Ferry was a huge mental milestone. At the psychological halfway point, Maine stopped feeling like a fantasy. Maryland was gentle, rolling terrain with well-maintained shelters and stone monuments.")
lines.append("")
lines.append("### 6. Pennsylvania (Days 49 to 57 | 222.5 miles | 24.7 mi/day)")
lines.append("Pennsylvania is famous for sharp, ankle-twisting rocks. You stop looking at mountain views and spend eight hours a day staring directly at your shoe placement. Shoe rubber wore down quickly on the jagged sandstone.")
lines.append("")
lines.append("Trail magic in Pennsylvania was remarkable. Coolers of cold soda and fresh fruit left at gravel road crossings kept morale high. At Pine Grove Furnace, I completed the traditional half-gallon ice cream challenge in one sitting.")
lines.append("")
lines.append("### 7. New Jersey and New York (Days 58 to 64 | 177.3 miles | 25.3 mi/day)")
lines.append("New Jersey was surprisingly flat and fast, producing my highest state average of 25.7 miles per day along the Kittatinny Ridge.")
lines.append("")
lines.append("New York brought short, steep rock scrambles like Bear Mountain. Hiking within forty miles of Manhattan felt surreal. You could see glimpses of distant skyline haze from granite knobs, then drop down into quiet wooded notches.")
lines.append("")
lines.append("### 8. Connecticut and Massachusetts (Days 65 to 70 | 147.6 miles | 24.8 mi/day)")
lines.append("Summer heat and mosquitoes peaked in southern New England. Connecticut followed the Housatonic River before climbing into the Berkshires. On Day 64, I logged 31.6 miles to Silver Hill, and on Day 70, I crossed Mount Greylock into Vermont.")
lines.append("")
lines.append("### 9. Vermont (Days 71 to 76 | 139.8 miles | 23.3 mi/day)")
lines.append("The Long Trail overlap brought classic green mountain terrain: deep mud, wooden bog planks, and cool mornings. On Day 75, I pushed 30.5 miles to Thistle Hill Shelter, crossing into Hanover, New Hampshire the next morning.")
lines.append("")
lines.append("### 10. New Hampshire (Days 77 to 83 | 138.7 miles | 19.8 mi/day)")
lines.append("New Hampshire reset the physical difficulty completely. The White Mountains are steep granite walls with massive vertical drop and exposed ridgelines above tree line.")
lines.append("")
lines.append("Climbing Franconia Ridge and Mount Washington was humbling. Daily mileage dropped below 20 miles per day despite pushing from 6:30 AM to dark. Every step required quad and knee braking on wet granite steps.")
lines.append("")
lines.append("### 11. Maine and Mount Katahdin (Days 84 to 98 | 213.2 miles | 20.9 mi/day)")
lines.append("Southern Maine started with Mahoosuc Notch, known as the trail's toughest mile. It is a jumble of giant boulders where you take off your pack and crawl through subterranean ice caves.")
lines.append("")
lines.append("After Monson, I entered the 100-Mile Wilderness: no paved roads, no town resupplies, just dense boreal forest, river fords, and root-choked singletrack. Carrying five days of food in a frameless pack made the first thirty miles heavy, but pace stayed above 21 miles per day.")
lines.append("")
lines.append("On Day 98 (August 26, 2009), I climbed the 5.2-mile final ascent of Mount Katahdin through the boulders of the Hunt Trail. Reaching Baxter Peak in cold, howling wind and touching the wooden sign marked the end of 98 days and 2,178 miles.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Complete 98-Day Distance Log")
lines.append("")
lines.append("The complete daily itinerary from my original trail spreadsheet:")
lines.append("")
lines.append("| Day | Date | Night Location / Shelter | Miles | Cumulative |")
lines.append("| :--- | :--- | :--- | :--- | :--- |")

for d in days:
    day_num = d["day"]
    loc = d["location"]
    miles = f"{d['miles']:.1f}"
    cum = f"{d['cumulative']:.1f}"
    # Generate approximate date
    lines.append(f"| Day {day_num} | Trail Day {day_num} | {loc} | {miles} | {cum} |")

lines.append("")
lines.append("---")
lines.append("")
lines.append("## Endurance and Recovery Takeaways")
lines.append("")
lines.append("Walking 22.5 miles every day for three months taught me practical realities about endurance that apply directly to physical training and work:")
lines.append("")
lines.append("1. **Pack weight dictates joint longevity:** An extra five pounds in a backpack is thousands of extra pounds of impact per knee every mile. Dropping my base weight to 5.73 pounds was the single reason my tendons survived 98 consecutive days without a stress injury.")
lines.append("2. **Consistent pace beats sporadic speed:** 22.5 miles a day does not require running. It requires avoiding long stationary breaks and keeping moving at 2.5 to 3.0 miles per hour for nine to ten hours.")
lines.append("3. **Radical mental simplification:** When your day consists entirely of four categories (miles, water, calories, and shelter), mental clutter disappears. The momentum of putting one foot in front of the other carries you through bad weather, steep terrain, and physical exhaustion.")
lines.append("")
lines.append("2,178 miles is a long way to walk. But once you break it down into daily milestones and stripped-down gear, it is simply a series of twenty-mile days.")

out_path = Path("src/content/blog/appalachian-trail-thru-hike-98-days.md")
out_path.write_text("\n".join(lines), encoding="utf-8")
print(f"Post generated successfully at {out_path} ({len(lines)} lines)!")
